version: 2.1
orbs:
  semver: tmo-orb/semver@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-tests:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      # SemVer update tests
      - semver/semver-increment
      - run:
          name: "Should work with default values"
          command:  |
            [[ $VERSION == "v0.0.1" ]] && echo "Patch added" || exit 134

      - run:
          name: "Load parameters to env"
          command: |
            echo "version=v0.0.0" > /home/circleci/.new_utils.config
            echo "option=p" >> /home/circleci/.new_utils.config
            echo "answer=NEW_VERSION" >> /home/circleci/.new_utils.config
      - semver/semver-increment:
          config_path: "/home/circleci/.new_utils.config"
      - run:
          name: "Should work with changed config path"
          command:  |
            [[ $VERSION == "v0.0.1" ]] && echo "Patch added" || exit 135

      - run:
          name: "Load parameters to env"
          command: |
            echo "version=v0.0.0" > /home/circleci/.utils.config
            echo "answer=VERSION" >> /home/circleci/.utils.config
      - semver/semver-increment
      - run:
          name: "Should add patch if no option is passed"
          command:  |
            [[ $VERSION == "v0.0.1" ]] && echo "Patch added" || exit 136

      - run:
          name: "Load parameters to env"
          command: |
            echo "version=v0.0.0" > /home/circleci/.utils.config
            echo "option=p" >> /home/circleci/.utils.config
            echo "answer=NEW_VERSION" >> /home/circleci/.utils.config
      - semver/semver-increment
      - run:
          name: "Should add assign to new NEW_VERSION variable"
          command:  |
            [[ $NEW_VERSION == "v0.0.1" ]] && echo "Patch added" || exit 137

      - run:
          name: "Load parameters to env"
          command: |
            echo "version=v0.0.0" > /home/circleci/.utils.config
            echo "option=p" >> /home/circleci/.utils.config
            echo "answer=VERSION" >> /home/circleci/.utils.config
      - semver/semver-increment
      - run:
          name: "Should add Patch"
          command:  |
            [[ $VERSION == "v0.0.1" ]] && echo "Patch added" || exit 138

      - run:
          name: "Load parameters to env"
          command: |
            echo "version=v0.0.1" > /home/circleci/.utils.config
            echo "option=m" >> /home/circleci/.utils.config
            echo "answer=VERSION" >> /home/circleci/.utils.config
      - semver/semver-increment
      - run:
          name: "Should add Minor and reset Patch"
          command:  |
            [[ $VERSION == "v0.1.0" ]] && echo "Minor added, Patch reseted" || exit 139

      - run:
          name: "Load parameters to env"
          command: |
            echo "version=v0.1.1" > /home/circleci/.utils.config
            echo "option=M" >> /home/circleci/.utils.config
            echo "answer=VERSION" >> /home/circleci/.utils.config
      - semver/semver-increment
      - run:
          name: "Should add Minor and reset Minor and Patch"
          command:  |
            [[ $VERSION == "v1.0.0" ]] && echo "Major added, Minor reseted, Patch reseted" || exit 140

      - run:
          name: "Load parameters to env"
          command: |
            echo "version=v0.1.3" > /home/circleci/.utils.config
            echo "option=mp" >> /home/circleci/.utils.config
            echo "answer=VERSION" >> /home/circleci/.utils.config
      - semver/semver-increment
      - run:
          name: "Should add Minor and reset Patch, add Patch"
          command:  |
            [[ $VERSION == "v0.2.1" ]] && echo "Minor added, Patch reseted, Patch added" || exit 141

      - run:
          name: "Load parameters to env"
          command: |
            echo "version=v0.1.3" > /home/circleci/.utils.config
            echo "option=Mp" >> /home/circleci/.utils.config
            echo "answer=VERSION" >> /home/circleci/.utils.config
      - semver/semver-increment
      - run:
          name: "Should add Major and reset Minor, Patch, add Patch"
          command:  |
            [[ $VERSION == "v1.0.1" ]] && echo "hMajor added, Minor reseted, Patch reseted, Patch added" || exit 142

      - run:
          name: "Load parameters to env"
          command: |
            echo "version=v2.1.1" > /home/circleci/.utils.config
            echo "option=Mmp" >> /home/circleci/.utils.config
            echo "answer=VERSION" >> /home/circleci/.utils.config
      - semver/semver-increment
      - run:
          name: "Should add Major and reset Minor, Patch, add Patch"
          command:  |
            [[ $VERSION == "v3.1.1" ]] && echo "Major added, Minor reseted, Patch reseted, Minor added, Patch added" || exit 143

      # Flag Value tests
      - run:
          name: "Load parameters to env"
          command: |
            echo "text='Test text with -r argument -d otherArgument' > /home/circleci/.utils.config
            echo "flag=r" >> /home/circleci/.utils.config
      - semver/flag-value:
      - run:
          name: "Should retrieve argument of -r flag"
          command:  |
            echo $FLAG_VALUE
            [[ $FLAG_VALUE == "argument" ]] && echo "Flag retrieved" || exit 144
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - command-tests:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: tmo-orb/semver
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
