version: 2.1
orbs:
  semver: tmo-orb/semver@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-tests:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - semver/semver-increment:
          level: "p"
          version: "v0.0.0"
      - run:
          name: "Should add Patch"
          command:  |
            [[ $VERSION == "v0.0.1" ]] && echo "Patch added" || exit 134
      - semver/semver-increment:
          level: "m"
          version: "v0.0.1"
      - run:
          name: "Should add Minor and reset Patch"
          command:  |
            [[ $VERSION == "v0.1.0" ]] && echo "Patch added" || exit 134
      - semver/semver-increment:
          level: "m"
          version: "v0.1.1"
      - run:
          name: "Should add Major and reset Minor, Patch"
          command:  |
            [[ $VERSION == "v1.0.0" ]] && echo "Patch added" || exit 134
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - command-tests:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: tmo-orb/semver
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
